name: The Peakbaggers
favicon: null
layout_spectrum: 0.1312548362184316
typography_spectrum: 0.3203262072056532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.10690826969221234
  lightness: 0.5292262239381671
  saturation: 0.47748981113545597
  rhythmicContrast: 0.10356115223839879
purpose: []
