name: The Peakbaggers
favicon: null
layout_spectrum: 0.61853
typography_spectrum: 0.72237
title: thepeakbaggers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed156a'
    - '#ffffff'
    - '#75757f'
    - '#16c1f3'
    - '#000000'
  brandStrength: 0.125
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
